### ISSUE TITLE
[BUG REPORT]

### ISSUE THREAD

**Issue by porkynes** [ottomated/CrewLink#380] opened 2020-12-14 09:24 UTC
# You MUST use this template or your issue will be deleted.

# Pre-Flight Checklist
Please use this checklist to avoid spamming:

1. [ ] I am not asking a question => use the [Discord](https://discord.gg/9mwuVNA) if you are
2. [ ] I am using the Steam version of Among Us
3. [ ] I have tried to use an [alternative voice server](https://status.crewl.ink/)
4. [ ] I have checked everyone in my lobby is on the same CrewLink server
5. [ ] I have used `Ctrl+R` on the CrewLink app when I can't hear some people (this is a known issue)
6. [ ] I have checked that the CrewLink server I'm using is up to date
7. [ ] I have a screenshot of any errors
8. [ ] I have checked that someone else has not reported this using the [search bar](https://github.com/ottomated/CrewLink/issues?q=is%3Aissue)

**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Version: [e.g. 1.1.5]

**Additional context**

So I the problem I have is that I can only hear and talk to one ppl out of 10.However my headset works perfectly and I used the correct voice server but still can't hear all of the ppl. Please help me. A lot of people are also having this problem please help us.

**Comment by porkynes** [comment] 2020-12-14 09:25
If someone else has the same problem and see this please comment in this so maybe the makers can see.

**Comment by oliverbooth** [comment] 2020-12-14 12:14
Good job filling out the issue template you did there, bud 🤦‍♂️

**Comment by drf-jpg** [comment] 2020-12-14 12:42
Could be related/a dupe of #248 (I list more potential dupes in that thread) and #272?

**Closed** 2020-12-15 03:04 UTC
