### ISSUE TITLE
[Suggestion] Voice distances

### ISSUE THREAD

**Issue by Maxmarval** [ottomated/CrewLink#49] opened 2020-11-29 05:01 UTC
It would be really nice to be able to edit the distance the person needs to be at to hear them by the lobby owner or the private voice server owner.

**Comment by Maxmarval** [comment] 2020-11-29 05:16
adding onto this, a ghost chat without alive players

**Comment by ottomated** [comment] 2020-11-29 10:33
Duplicate of #7

**Closed by ottomated** 2020-11-29 10:33 UTC
