### ISSUE TITLE
[Suggestion] Added Functionality - Optional Feature: Communication Sabotage disabling Proximity chat

### ISSUE THREAD

**Issue by superzomar** [ottomated/CrewLink#201] opened 2020-12-07 15:25 UTC
While looking at the program I was trying to figure cool new things that can be added to the app and make it dynamic to in game states.  I noticed how in while in game people could still here each other while the light where out and they couldn't see each other.  This got me to thinking if there should be a way to force a mute on all player.  This idea does not make sense for light sabotage but it this idea makes perfect sense in conjunction with the communications sabotage and fits well with all the functionality that sabotage already has in game.  I just wanted to make the suggestion as I didn't see it anyone else make it and thought it might make for more dynamic and interesting game play.

--- Ticket details for Dev -- (if you would like to use it)

----------------------------------------------------------------------------------------------------------------------------------------------
{Feature} Communication Sabotage Interrupt

{Summary} While the Communication sabotage is active the voice proximity feature should be the option to be disabled.  This option will add dynamics to game play that do not currently exist inside the application.

{Requirements} The following should be implemented to not remove current functionality while adding the new functionality:
    - Option in menu for communication sabotage to disable proximity chat
    - Add Sabotage state to the code base (didn't see it when I took my quick look at the code)
    - Implement disabling Proximity chat for all players during communications sabotage
    - Replace user icons in interface with "[COMMS DISABLED]" similar to how other devices show it in game (see below for 
            Example)
    - Re-enable voice chat during meetings while Communications Sabotage is active
    - Re-disable voice chat after meetings while Communications Sabotage is active

----------------------------------------------------------------------------------------------------------------------------------------------

![Comms_Disabled_Doorlog_ In_Game_Example](https://user-images.githubusercontent.com/26910418/101368974-67dc1780-386d-11eb-9687-bbc148658ab7.png)

Additional Ideas
    - Imposters can still chat during sabotage
    - Voice chat disabled while in meeting during Communications Sabotage - (I personally don't believe this to be a good idea 
            but I had it and want to record it)

I encourage anyone else who thinks they have something to add to speak.  I don't know how good this would be but I wanted to get the idea out there.

**Comment by ottomated** [comment] 2020-12-08 06:07
Duplicate of #7

**Closed by ottomated** 2020-12-08 06:07 UTC
