### ISSUE TITLE
[BUG REPORT]

### ISSUE THREAD

**Issue by BocianDos** [ottomated/CrewLink#317] opened 2020-12-11 09:33 UTC
# You MUST use this template or your issue will be deleted.

# Pre-Flight Checklist
Please use this checklist to avoid spamming:

1. [X] I am not asking a question => use the [Discord](https://discord.gg/9mwuVNA) if you are
2. [X] I am using the Steam version of Among Us
3. [X] I have tried to use an [alternative voice server](https://status.crewl.ink/)
4. [X] I have checked everyone in my lobby is on the same CrewLink server
5. [X] I have used `Ctrl+R` on the CrewLink app when I can't hear some people (this is a known issue)
6. [X] I have checked that the CrewLink server I'm using is up to date
7. [X] I have a screenshot of any errors
8. [X] I have checked that someone else has not reported this using the [search bar](https://github.com/ottomated/CrewLink/issues?q=is%3Aissue)

**Describe the bug**
I can't hear my friends since first versions of CrewLink. After joining a lobby we can't hear each other. Everyone sees green circles around them when they speak, but there is no circle around others. We have tried private servers and public ones too.

**Screenshots**
https://imgur.com/a/AH7OZkg

**Desktop**
 - OS: Windows 10
 - Version:1.1.6

**Comment by TheSpringBoy** [comment] 2020-12-11 09:44
Its duplicate of #149 
any way. swap you isp or use VPN. it should solve the problem

**Closed** 2020-12-11 11:47 UTC
Labels: bug
