### ISSUE TITLE
Everything is read even when they had it open even when i talk it says red instead of green

### ISSUE THREAD

**Issue by murky1k** [ottomated/CrewLink#53] opened 2020-11-29 07:00 UTC
![crewlink 11_29_2020 1_59_57 AM](https://user-images.githubusercontent.com/75197103/100535414-aa0ab680-31e6-11eb-9de4-f6e37645add4.png)

**Comment by ottomated** [comment] 2020-11-29 10:34
Duplicate of #45. Host a private server.

**Closed by ottomated** 2020-11-29 10:34 UTC
