### ISSUE TITLE
Crewlink 1.1.6 saying wrong among us ver.

### ISSUE THREAD

**Issue by smokingamer** [ottomated/CrewLink#314] opened 2020-12-11 06:29 UTC
# You MUST use this template or your issue will be deleted.

# Pre-Flight Checklist
Please use this checklist to avoid spamming:

1. [x] I am not asking a question => use the [Discord](https://discord.gg/9mwuVNA) if you are
2. [x] I am using the Steam version of Among Us
3. [x] I have tried to use an [alternative voice server](https://status.crewl.ink/)
4. [x] I have checked everyone in my lobby is on the same CrewLink server
5. [x] I have used `Ctrl+R` on the CrewLink app when I can't hear some people (this is a known issue)
6. [x] I have checked that the CrewLink server I'm using is up to date
7. [x] I have a screenshot of any errors
8. [x] I have checked that someone else has not reported this using the [search bar](https://github.com/ottomated/CrewLink/issues?q=is%3Aissue)

**Describe the bug**
When I open the crewlink app after the 1.1.6 update, it pops up with an error telling me I am using the wrong version of Among Us, even though it is fully up to date

**To Reproduce**
Steps to reproduce the behaviour:
Just open the program

**Expected behaviour**
To run normally

**Screenshots**
![Screenshot 2020-12-10 222912](https://user-images.githubusercontent.com/75766299/101871097-cf2cec80-3b37-11eb-9ab1-123e78b91103.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 1.1.6

**Additional context**

**Comment by Skkkitzo** [comment] 2020-12-11 06:31
You haven't provided any information as to what the bug is about. You copied a blank format.
Please elaborate.

**Comment by smokingamer** [comment] 2020-12-11 06:35
I apologize, just updated it

> You haven't provided any information as to what the bug is about. You copied a blank format.
> Please elaborate.

**Comment by Skkkitzo** [comment] 2020-12-11 06:38
The error that you are showing here is likely a duplicate of #303, the fix of which is to change voice server.

**Comment by BocianDos** [comment] 2020-12-11 09:09
I have the same issue

**Comment by ottomated** [comment] 2020-12-11 11:48
Use an up-to-date voice server.

**Closed by ottomated** 2020-12-11 11:48 UTC
Labels: bug
