### ISSUE TITLE
does not detect for non steam among us

### ISSUE THREAD

**Issue by doabi** [ottomated/CrewLink#62] opened 2020-11-29 20:07 UTC
![Késdasdaspkivágás](https://user-images.githubusercontent.com/75222378/100555877-b3575a00-329e-11eb-8b16-455d5271cf5e.JPG)
I bought among us online but crewlink cant detect it as it is not bought on steam and I also tried add among us to steam like a non steam game and still not working

**Comment by neil-lobo** [comment] 2020-11-30 03:48
I'm pretty sure you need to be using the Steam version of the game. If you bought it on itch.io you were also provided a free Steam key for the game.

**Comment by ottomated** [comment] 2020-11-30 07:48
Duplicate of #14

**Closed by ottomated** 2020-11-30 07:48 UTC
