### ISSUE TITLE
[BUG REPORT] Unfixable Black Screen

### ISSUE THREAD

**Issue by Pugggg** [ottomated/CrewLink#479] opened 2020-12-29 23:34 UTC
# You MUST use this template or your issue will be deleted.

# Pre-Flight Checklist
Please use this checklist to avoid spamming:

1. [✓ ] I am not asking a question => use the [Discord](https://discord.gg/9mwuVNA) if you are
2. [✓ ] I am using the Steam version of Among Us
3. [ ✓] I have tried to use an [alternative voice server](https://status.crewl.ink/)
4. [ ✓] I have checked everyone in my lobby is on the same CrewLink server
5. [✓ ] I have used `Ctrl+R` on the CrewLink app when I can't hear some people (this is a known issue)
6. [✓ ] I have checked that the CrewLink server I'm using is up to date
7. [✓ ] I have a screenshot of any errors
8. [✓ ] I have checked that someone else has not reported this using the [search bar](https://github.com/ottomated/CrewLink/issues?q=is%3Aissue)

**Describe the bug**
Crewlink comes to a dark screen yet you cannot fix it, nor hear anyone.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open Crewlink
2. Join a lobby for proximity chat.
3. Wait about 2 seconds

**Expected behaviour**

Crewlink Should Work
**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 1.2.0

**Additional context**
DOES NOT HAPPEN ON ALL OCCASIONS!
![image](https://user-images.githubusercontent.com/76756348/103320717-1d793100-49fc-11eb-9edc-26397bf7f7c9.png)

**Comment by Molgarath** [comment] 2020-12-30 02:01
I also have this issue! I've had this exact issue since the moment CrewLink updated from 1.1.6 to 1.2.0. The only difference is that it does always happen for me. I have six family and friends who all have the exact same issue.

**Comment by itismejoey** [comment] 2020-12-30 03:52
I can also confirm this happening.

**Comment by Pugggg** [comment] 2020-12-30 16:26
It doesn't have the black screen error when you are hosting a game though, and not all people have it. I reccomend completely deleting everything that somewhat that relates to crewlink and reinstall it. That's what I'm doing right now

**Comment by elcanadiano** [comment] 2020-12-30 20:05
Should be a dupe of this task:

https://github.com/ottomated/CrewLink/issues/472

Should have been fixed with this PR:

https://github.com/ottomated/CrewLink/pull/470

**Comment by vas4oo** [comment] 2020-12-30 22:50
It's not fixed in 1.2.1 !

**Comment by Mytre** [comment] 2020-12-31 00:30
Can confirm this bug, its a big issue for many players. blank screen after joining

**Comment by ottomated** [comment] 2020-12-31 01:17
you're probably on an unofficial server, or you have someone in your lobby on an old version of CrewLink.

**Closed by ottomated** 2020-12-31 01:17 UTC
Labels: bug
