### ISSUE TITLE
[BUG REPORT]

### ISSUE THREAD

**Issue by XDGamin13254** [ottomated/CrewLink#464] opened 2020-12-27 05:53 UTC
# You MUST use this template or your issue will be deleted.

# Pre-Flight Checklist
Please use this checklist to avoid spamming:

1. [x] I am not asking a question => use the [Discord](https://discord.gg/9mwuVNA) if you are
2. [x] I am using the Steam version of Among Us
3. [ ] I have tried to use an [alternative voice server](https://status.crewl.ink/)
4. [x] I have checked everyone in my lobby is on the same CrewLink server
5. [x] I have used `Ctrl+R` on the CrewLink app when I can't hear some people (this is a known issue)
6. [x] I have checked that the CrewLink server I'm using is up to date
7. [ ] I have a screenshot of any errors
8. [ ] I have checked that someone else has not reported this using the [search bar](https://github.com/ottomated/CrewLink/issues?q=is%3Aissue)

**Describe the bug**
Whenever I join a lobby, it shows everyone as not connected to the internet, and then my screen goes black

**To Reproduce**
Steps to reproduce the behaviour:
1. Open Crewlink
2. Join a private among us voice chat server

**Expected behaviour**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Version: [e.g. 1.1.5]

**Additional context**

**Comment by dustinlynch** [comment] 2020-12-27 06:21
Possible duplicate of #462

**Comment by dustinlynch** [comment] 2020-12-27 06:22
Possible duplicate of #462, @XDGamin13254 - can you confirm the screenshots on #462 are what occurs on your screen? Also, is this occurring with Crew Link 1.2?

**Comment by ottomated** [comment] 2020-12-27 06:23
Are you using a non-default voice server? And is anyone in your lobby still on 1.1.6?

**Comment by cody62394** [comment] 2020-12-28 02:32
When I use a non-default voice server this is happening. anyone know why?

**Closed** 2020-12-28 03:23 UTC
Labels: bug
