### ISSUE TITLE
Support for Crossover

### ISSUE THREAD

**Issue by Raphael777777** [ottomated/CrewLink#296] opened 2020-12-10 06:47 UTC
Can you please get this to support crossover, as I play on mac, but use crossover to use windows apps like Among on Steam. However this does not support crossover. Do you think its possible to make it support 
<img width="421" alt="Screen Shot 2020-12-10 at 5 46 45 pm" src="https://user-images.githubusercontent.com/75773581/101731449-c2949e00-3b0f-11eb-9b2a-aa1529146226.png">
crossover?

**Comment by TheSpringBoy** [comment] 2020-12-10 09:17
I am pretty sure its a duplicate of #4

**Closed** 2020-12-10 09:52 UTC
Labels: enhancement
