### ISSUE TITLE
3D audio effect, being able to hear right or left.

### ISSUE THREAD

**Issue by LeandreBl** [ottomated/CrewLink#56] opened 2020-11-29 16:15 UTC
It would be awesome to hear people in the right or left ear, depending on their position.

**Comment by geisterfurz007** [comment] 2020-11-29 20:06
Duplicate of https://github.com/ottomated/CrewLink/issues/55?

**Comment by ottomated** [comment] 2020-11-29 21:40
Duplicate of #55

**Closed by ottomated** 2020-11-29 21:40 UTC
