### ISSUE TITLE
The same two people can only hear eachother and no one else

### ISSUE THREAD

**Issue by Nu7M3g** [ottomated/CrewLink#119] opened 2020-12-04 21:53 UTC
Hey!

There are 6 people in our lobby, four of us can hear eachother but not the other two, the other two can hear eachother and not the four others.

Any ideas?

**Comment by xenoguy** [comment] 2020-12-04 22:02
the app uses webrtc to connect people i think, have people run this test and see if it works or not:

https://test.webrtc.org/

**Comment by SizableShrimp** [comment] 2020-12-04 23:20
Seems to be similar/duplicate of #47

**Comment by ottomated** [comment] 2020-12-05 00:47
Duplicate of #47

**Closed by ottomated** 2020-12-05 00:47 UTC
