### ISSUE TITLE
ETIMEDOUT error

### ISSUE THREAD

**Issue by hobieg** [ottomated/CrewLink#50] opened 2020-11-29 05:18 UTC
Having some issues starting the app, I have the Steam Among Us version, all updated on non-beta. Checked firewall settings and allowed crew link through, tried restarting and reinstalling multiple times. But about 15 seconds into starting the app and using the app to open among us, I get this error message. 

> Couldn't fetch the latest game offsets from the server: http://54.193.94.35:9736/2020.11.17.yml. Error: connect ETIMEDOUT 54.193.94.35:9736
> 
> Restart the app after you fix this.

**Comment by demonricky** [comment] 2020-11-29 06:37
same here

**Comment by LoopedBard3** [comment] 2020-11-29 06:38
Please check out #45, I just posted a method for fixing the error that worked for me. It consists of changing the voice server IP address from 54.193.94.35 to 209.182.233.230. This IP address can also be found by doing a hostname lookup for ottomated.net through any hostname lookup service (ottomated.net is the default voice server).

**Comment by ottomated** [comment] 2020-11-29 10:34
Duplicate of #45. Host a private server.

**Closed by ottomated** 2020-11-29 10:34 UTC
