### ISSUE TITLE
it detects that im the menu when im in a lobby

### ISSUE THREAD

**Issue by ImThomasBTW** [ottomated/CrewLink#63] opened 2020-11-29 21:01 UTC
i tried everything, redownloading crewlink and amongus and nothing, heres a screenshot
![image](https://user-images.githubusercontent.com/63749064/100553489-e4b73200-326c-11eb-9a1d-1f88fd605971.png)
pls help

**Comment by ottomated** [comment] 2020-11-29 21:42
Duplicate of #28

**Closed by ottomated** 2020-11-29 21:42 UTC
