### ISSUE TITLE
Only able to hear one other player, while he is the only one who can hear me, but also all other players.

### ISSUE THREAD

**Issue by BlueNagrom** [ottomated/CrewLink#54] opened 2020-11-29 07:39 UTC
I'm playing in a lobby with 10 people we all show up as connected properly without a red circle, and when the one other player talks his circle lights up and mine does too. We're using a private server that shows up with 10 connections. I'm the only one in the lobby experiencing this issue. Can provide more details if needed. Thanks.
![CrewLink](https://user-images.githubusercontent.com/11687437/100536072-01069080-31d3-11eb-980a-af6aedc4d38b.png)

**Comment by ottomated** [comment] 2020-11-29 10:35
This is related to NAT types or something of the sort and is therefore out of scope

**Closed by ottomated** 2020-11-29 10:35 UTC
Labels: wontfix

**Comment by uzervlad** [comment] 2020-11-29 11:32
> This is related to NAT types or something of the sort and is therefore out of scope

I don't think so, as I've ran into the same issue on the default server

**Comment by vanderpipou** [comment] 2020-11-29 23:31
> I don't think so, as I've ran into the same issue on the default server
Same problem here on my private server (using docker) and on the default server.

**Comment by ToxiWoxi** [comment] 2020-12-11 07:28
In testing this myself, I have confirmed that this is a NAT issue.

**Comment by X-Sace** [comment] 2020-12-11 17:26
**I found a fix Try using a VPN if you wanna avoid vpn do port forwarding but its harder to use because when you switch voice server you always have to change the port of the port forwarding and must know the port that the voice server your using**

**Comment by KayeLeesi** [comment] 2020-12-21 12:34
how do you fix it using the VPN? Sorry, kind of a noob at this.
