### ISSUE TITLE
[BUG REPORT] CrewLink not loading, only displaying a grey window

### ISSUE THREAD

**Issue by nor7hs** [ottomated/CrewLink#309] opened 2020-12-11 03:34 UTC
# You MUST use this template or your issue will be deleted.

# Pre-Flight Checklist
Please use this checklist to avoid spamming:

1. [x] I am not asking a question => use the [Discord](https://discord.gg/9mwuVNA) if you are
2. [x] I am using the Steam version of Among Us
3. [x ] I have tried to use an [alternative voice server server](https://status.crewl.ink/)
4. [x] I have checked everyone in my lobby is on the same CrewLink server
5. [x] I have used `Ctrl+R` on the CrewLink app when I can't hear some people (this is a known issue)
6. [x] I have checked that the CrewLink server I'm using is up to date
7. [x] I have a screenshot of any errors
8. [x] I have checked that someone else has not reported this using the [search bar](https://github.com/ottomated/CrewLink/issues?q=is%3Aissue)

**Describe the bug**

when i open crewlink, i get a grey screen. nothing else. tried uninstalling/reinstalling. installing older versions than 1.1.6 kets me open with a 502 error, restarting leads me to the same grey screen. running in admin or compat mode does nothing.

**To Reproduce**
Steps to reproduce the behaviour:
load the program.

**Expected behaviour**

the program to load

**Screenshots**

https://gyazo.com/07a432d420a19734077b6934e00a4b56

**Desktop (please complete the following information):**
 - OS: Windows 10 1909
 - Version: 1.1.6

**Additional context**

**Comment by ottomated** [comment] 2020-12-11 03:38
Duplicate of #308, comment there

**Closed by ottomated** 2020-12-11 03:38 UTC
Labels: bug
