### ISSUE TITLE
Red Rings For Everyone

### ISSUE THREAD

**Issue by EmiPiri** [ottomated/CrewLink#48] opened 2020-11-29 04:31 UTC
Everyone including me has a red ring, it was working yesterday I don't know why its happening.

**Comment by Maxmarval** [comment] 2020-11-29 05:34
The servers are down you can create a privaite one

**Comment by ottomated** [comment] 2020-11-29 10:36
Duplicate of #45. Create a private server.

**Closed by ottomated** 2020-11-29 10:36 UTC
